
### Gemini generateContent
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
Content-Type: application/json
x-goog-api-key:

{
    "contents": [
        {
            "parts": [
            {
                "text": "こんにちは、今日の天気を教えて"
            }
            ]
        }
    ]
}
