version = 0.1

[default.deploy.parameters]
stack_name = "lambda-hexagonal-architecture-sample"
resolve_s3 = true
s3_prefix = "lambda-hexagonal-architecture-sample"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true

[default.global.parameters]
region = "ap-northeast-1"
