import os
from typing import Callable, Mapping, Optional, Sequence
import cdk_nag
import aws_cdk.aws_iam as aws_iam
from aws_cdk import BundlingOptions, aws_lambda, Stack
from constructs import Construct


class AppProjectFunction(Construct):
    """
    Lambda 関数構築コンストラクト

    コード をバンドルし、IAM ロール、権限、トレーシングを設定して
    Lambda 関数を作成
    """

    def __init__(
        self,
        scope: Construct,
        id: str,
        entry: str,  # ハンドラーの相対パス（app/entrypoints/api など）
        root: str,  # ソースコードのルート（app など）
        runtime: aws_lambda.Runtime,  # Lambda ランタイム（Python 3.9 など）
        layers: Sequence[aws_lambda.ILayerVersion],  # Lambda レイヤー（共有ライブラリ）
        function_name: str,  # Lambda 関数名
        handler: str = "handler",  # ハンドラー関数名（デフォルト: handler）
        handler_filename: str = "handler.py",  # ハンドラーファイル名
        environment: Optional[Mapping[str, str]] = None,  # 環境変数
        permissions: Sequence[Callable[[aws_iam.IGrantable], aws_iam.Grant]] = [],  # IAM権限付与関数
    ) -> None:
        super().__init__(scope, id)

        # 現在のスタックを取得（リージョン、アカウントID取得用）
        stack = Stack.of(self)

        # ========== コード準備 ==========
        # ソースコードを Docker コンテナでバンドル
        current_dir = "."
        code = aws_lambda.Code.from_asset(
            path=current_dir,
            bundling=BundlingOptions(
                image=runtime.bundling_image,  # ランタイム対応の Docker イメージ
                command=[
                    "bash",
                    "-c",
                    f"rsync -r {root} /asset-output",  # ソースコードを出力ディレクトリにコピー
                ],
            ),
        )

        # ========== IAM ポリシー設定 ==========
        # Lambda 用のマネージドポリシー を作成（CloudWatch ログと X-Ray 権限）
        lambda_policy = aws_iam.ManagedPolicy(self, 'lambda-managed-policy',
            managed_policy_name=f"{function_name}-managed-policy",
            statements=[
                # CloudWatch ログ作成権限
                aws_iam.PolicyStatement(
                    actions=[
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                    ],
                    resources=[
                        f"arn:aws:logs:{stack.region}:{stack.account}:log-group:{function_name}",
                        f"arn:aws:logs:{stack.region}:{stack.account}:log-group:{function_name}:log-stream:*"
                    ],
                ),
                # X-Ray トレーシング権限
                aws_iam.PolicyStatement(
                    actions=[
                        "xray:PutTraceSegments",
                        "xray:PutTelemetryRecords",
                    ],
                    resources=['*'],  # X-Ray は特定リソースの指定不要
                )
            ],
        )

        # ========== セキュリティスキャン対応 ==========
        # cdk_nag による ワイルドカード権限の警告を抑制（根拠あり）
        cdk_nag.NagSuppressions.add_resource_suppressions(
            construct=lambda_policy,
            suppressions=[
                cdk_nag.NagPackSuppression(
                    id="AwsSolutions-IAM5",
                    reason="Log stream IDs are autogenerated.",
                    applies_to=["Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:simple-crud-api:log-stream:*"]
                ),
                cdk_nag.NagPackSuppression(
                    id="AwsSolutions-IAM5",
                    reason="X-Ray actions have no resources for the policy.",
                    applies_to=["Resource::*"]
                ),
            ],
        )

        # ========== IAM ロール作成 ==========
        # Lambda が引き受けるロール
        lambda_role = aws_iam.Role(self, 'lambda-role',
            assumed_by=aws_iam.ServicePrincipal("lambda.amazonaws.com"),
            role_name=f"{function_name}-role",
            managed_policies=[lambda_policy],
        )

        # ========== Lambda 関数作成 ==========
        # ハンドラーパスを構築（例：app/entrypoints/api/handler.handler）
        self._func = aws_lambda.Function(
            self,
            "AppProjectFunction",
            code=code,
            runtime=runtime,
            handler=f"{entry}/{os.path.splitext(handler_filename)[0]}.{handler}",
            layers=layers,  # 共有ライブラリレイヤーをアタッチ
            function_name=function_name,
            environment=environment,  # 環境変数を設定
            tracing=aws_lambda.Tracing.ACTIVE,  # X-Ray トレーシングを有効化
            role=lambda_role
        )

        # ========== 追加のセキュリティ設定 ==========
        # インラインポリシーの警告を抑制
        default_policy = [p for p in lambda_role.node.children if isinstance(p, aws_iam.Policy)][0]
        cdk_nag.NagSuppressions.add_resource_suppressions(
            construct=default_policy,
            suppressions=[
                cdk_nag.NagPackSuppression(
                    id="AwsSolutions-IAM5",
                    reason="X-Ray actions have no resources for the policy.",
                    applies_to=["Resource::*"]
                ),
            ],
        )

        # ========== 追加権限の付与 ==========
        # DynamoDB アクセスなどの権限を付与
        for p in permissions:
            p(self._func)

    @property
    def function(self) -> aws_lambda.Function:
        """作成された Lambda 関数インスタンスを取得"""
        return self._func
