name: Deploy CloudFormation

on:
  push:
    branches:
      - main
    paths:
      - "template.yaml"
      - "app/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::176355978867:role/github-deploy-role
          aws-region: ap-northeast-1

      - name: Package template
        run: |
          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-vkuzfrstta1e  \
            --output-template-file packaged-template.yaml

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
            --template-file packaged-template.yaml \
            --stack-name lambda-hexagonal-architecture-sample \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
